spring.application.name=eureka-discovery-server
server.port=8761

# This node IS the registry, so it doesn't need to register with itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
